### ISSUE TITLE
Spec licensing

### ISSUE THREAD

**Issue by ahelwer** [visualzhou/mongo-repl-tla#2]
Hello! I am collecting TLA+ specs for the examples repo and am wondering what license these are under, could you please add one when you have time? Thank you!

**Comment by ahelwer** [comment]
Hi @visualzhou just wondering whether you'd be able to quickly confirm these specs are licensed under MIT or something similarly permissive! Just replying here in this issue will suffice.

**Comment by visualzhou** [comment]
Thanks @ahelwer! This spec is the origin of the specs in [the MongoDB repo](https://github.com/mongodb/mongo/tree/83f802cf1beb0e402d0b1c57609ba8279eca412d/src/mongo/tla_plus). Since the specs there are under "Creative Commons Attribution-3.0 United States License", I'd say this is also under "CC BY 3.0 US".
